docker service rm $(docker service ls -q)
docker kill $(docker image ls -q)
docker container rm $(docker container ls -a -q)
docker image rm $(docker image ls -q)
docker volume rm $(docker volume ls -q)
docker network rm -f $(docker network ls -q)
