const projectPrefix = '/Users/hello/Projects/ethang'

export const projects = {
  scripts: {
    path: `${projectPrefix}/scripts`,
    updateDeps: true,
    isTurboRepo: false,
    build: false,
    lint: false,
    publish: false,
    branch: 'master',
  },
  eslintConfig: {
    path: `${projectPrefix}/eslint-config-ethang`,
    updateDeps: true,
    isTurboRepo: false,
    build: false,
    lint: true,
    publish: true,
    branch: 'master',
  },
  hooks: {
    path: `${projectPrefix}/hooks`,
    updateDeps: true,
    isTurboRepo: false,
    build: false,
    lint: false,
    publish: true,
    branch: 'main',
  },
  useForm: {
    path: `${projectPrefix}/use-form`,
    updateDeps: true,
    isTurboRepo: false,
    build: false,
    lint: false,
    publish: true,
    branch: 'master',
  },
  fetch: {
    path: `${projectPrefix}/fetch`,
    updateDeps: true,
    isTurboRepo: false,
    build: false,
    lint: false,
    publish: true,
    branch: 'master',
  },
  website: {
    path: `${projectPrefix}/website`,
    updateDeps: true,
    isTurboRepo: false,
    build: true,
    lint: false,
    publish: false,
    branch: 'master',
  },
  introspect: {
    path: `${projectPrefix}/introspect`,
    updateDeps: true,
    isTurboRepo: false,
    build: true,
    lint: true,
    publish: false,
    branch: 'main',
  },
  sterettAdmin: {
    path: `${projectPrefix}/sterett-admin`,
    updateDeps: true,
    isTurboRepo: false,
    build: false,
    lint: true,
    publish: false,
    branch: 'master',
  },
  sterettClient: {
    path: `${projectPrefix}/sterett-client`,
    updateDeps: true,
    isTurboRepo: false,
    build: true,
    lint: true,
    publish: false,
    branch: 'master',
  },
  examples: {
    path: `${projectPrefix}/examples`,
    updateDeps: false,
    isTurboRepo: true,
    build: true,
    lint: true,
    publish: false,
    branch: 'main',
  }
}
